### ISSUE TITLE
Slides to introduce them to some simple refactors

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-bootcamp-fundamentals-2#3]
Suggest we cover rename, extract variable (and field and constant), and extract method. We need an exercise that either exercises all three or one at once.

**Comment by alectunbridge** [comment]
Isn't this is going to be tricky for the Pythoners.....?

**Comment by mrmanc** [comment]
Genuine *shrug*. We should ask a Pythoner, but from what I can see things like Pycharm support this.

* https://www.jetbrains.com/help/pycharm/rename-refactorings.html
* https://www.jetbrains.com/help/pycharm/extract-variable.html
* https://www.jetbrains.com/help/pycharm/extract-method.html
